import React, { useState, useEffect, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, Globe, Star, Upload } from 'lucide-react';
import BookmarkIcon from './BookmarkIcon';

interface Bookmark {
  id: string;
  title: string;
  url: string;
  iconType?: 'favicon' | 'lucide' | 'custom';
  lucideIcon?: string;
  iconColor?: string;
  customIconUrl?: string;
  isDashboardWidget?: boolean;
  type?: 'bookmark' | 'folder' | 'note';
  useCoverIcon?: boolean;
  isFullCover?: boolean;
  notes?: string;
  useQuickNoteOnHover?: boolean;
  pinToEnd?: boolean;
}

interface AddBookmarkModalProps {
  isOpen: boolean;
  onClose: () => void;
  onAdd: (title: string, url: string, iconProps: any) => void;
  onEdit: (id: string, title: string, url: string, iconProps: any) => void;
  editData: Bookmark | null;
}

const COMMON_ICONS = [
  'Globe', 'Star', 'Heart', 'Bookmark', 'Image', 'Video', 'Music', 'Book', 'FileText', 'Folder', 
  'Home', 'User', 'Settings', 'Briefcase', 'Camera', 'Code', 'Database', 'Mail', 'Map', 'Monitor', 
  'Phone', 'ShoppingBag', 'Terminal', 'PenTool', 'Tv', 'Wifi'
];

const PRESET_COLORS = ['#ffffff', '#FF5733', '#33FF57', '#3357FF', '#F1C40F', '#9B59B6', '#E67E22', '#1ABC9C', '#E74C3C', '#34495E'];

const AddBookmarkModal: React.FC<AddBookmarkModalProps> = ({ 
  isOpen, 
  onClose, 
  onAdd, 
  onEdit, 
  editData 
}) => {
  const [title, setTitle] = useState('');
  const [url, setUrl] = useState('');
  const [isTitleAutoGenerated, setIsTitleAutoGenerated] = useState(true);
  const [bookmarkType, setBookmarkType] = useState<'bookmark' | 'folder' | 'note'>('bookmark');
  const [noteContent, setNoteContent] = useState('');
  
  // Icon State
  const [iconType, setIconType] = useState<'favicon' | 'lucide' | 'custom'>('favicon');
  const [lucideIcon, setLucideIcon] = useState('Globe');
  const [iconColor, setIconColor] = useState('#ffffff');
  const [customIconUrl, setCustomIconUrl] = useState('');
  const [isDashboardWidget, setIsDashboardWidget] = useState(false);
  const [useCoverIcon, setUseCoverIcon] = useState(false);
  const [isFullCover, setIsFullCover] = useState(false);
  const [isFetchingTitle, setIsFetchingTitle] = useState(false);
  const [quickNote, setQuickNote] = useState('');
  const [useQuickNoteOnHover, setUseQuickNoteOnHover] = useState(false);
  const [pinToEnd, setPinToEnd] = useState(false);
  
  const fileInputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    if (editData) {
      setTitle(editData.title);
      setUrl(editData.url);
      setIsTitleAutoGenerated(false);
      setBookmarkType(editData.type || 'bookmark');
      setIconType(editData.iconType || 'favicon');
      setLucideIcon(editData.lucideIcon || 'Globe');
      setIconColor(editData.iconColor || '#ffffff');
      setCustomIconUrl(editData.customIconUrl || '');
      setIsDashboardWidget(editData.isDashboardWidget || false);
      setUseCoverIcon(editData.useCoverIcon || false);
      setIsFullCover(editData.isFullCover || false);
      setNoteContent(editData.notes || '');
      setQuickNote(editData.quickNote || '');
      setUseQuickNoteOnHover(editData.useQuickNoteOnHover || false);
      setPinToEnd(editData.pinToEnd || false);
      if (editData.type === 'note') setIconType('lucide'), setLucideIcon('StickyNote');
    } else {
      setTitle('');
      setUrl('');
      setIsTitleAutoGenerated(true);
      setBookmarkType('bookmark');
      setIconType('favicon');
      setLucideIcon('Globe');
      setIconColor('#ffffff');
      setCustomIconUrl('');
      setIsDashboardWidget(false);
      setUseCoverIcon(false);
      setIsFullCover(false);
      setNoteContent('');
      setQuickNote('');
      setUseQuickNoteOnHover(false);
      setPinToEnd(false);
    }
  }, [editData, isOpen]);

  const generateTitleFromUrl = (inputUrl: string) => {
    try {
      const fullUrl = inputUrl.startsWith('http') ? inputUrl : `https://${inputUrl}`;
      const hostname = new URL(fullUrl).hostname;
      const parts = hostname.replace(/^www\./, '').split('.');
      if (parts.length > 0 && parts[0]) {
        const name = parts[0];
        return name.charAt(0).toUpperCase() + name.slice(1);
      }
    } catch {
      return '';
    }
    return '';
  };

  const getYouTubeVideoId = (url: string): string | null => {
    try {
      const u = new URL(url.startsWith('http') ? url : `https://${url}`);
      // Standard: youtube.com/watch?v=ID
      if (u.hostname.includes('youtube.com') && u.searchParams.get('v')) {
        return u.searchParams.get('v');
      }
      // Short: youtu.be/ID
      if (u.hostname === 'youtu.be') {
        return u.pathname.slice(1).split('?')[0] || null;
      }
      // Embed: youtube.com/embed/ID
      const embedMatch = u.pathname.match(/\/embed\/([^/?]+)/);
      if (embedMatch) return embedMatch[1];
    } catch {
      // ignore
    }
    return null;
  };

  const fetchYouTubeTitle = async (url: string) => {
    setIsFetchingTitle(true);
    try {
      const oEmbedUrl = `https://www.youtube.com/oembed?url=${encodeURIComponent(url)}&format=json`;
      const res = await fetch(oEmbedUrl);
      if (res.ok) {
        const data = await res.json();
        if (data.title) {
          setTitle(data.title);
          setIsTitleAutoGenerated(false);
        }
      }
    } catch {
      // oEmbed failed — fallback already set
    } finally {
      setIsFetchingTitle(false);
    }
  };

  const handleUrlChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const newUrl = e.target.value;
    setUrl(newUrl);

    if (!editData && isTitleAutoGenerated) {
      const suggested = generateTitleFromUrl(newUrl);
      setTitle(suggested);

      // If it's a YouTube URL, fetch the real title
      const videoId = getYouTubeVideoId(newUrl);
      if (videoId) {
        const fullUrl = newUrl.startsWith('http') ? newUrl : `https://${newUrl}`;
        fetchYouTubeTitle(fullUrl);
      }
    }
  };

  const handleTitleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setTitle(e.target.value);
    setIsTitleAutoGenerated(false);
  };

  const handleImageUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = (event) => {
      const img = new Image();
      img.onload = () => {
        const canvas = document.createElement('canvas');
        const MAX_SIZE = 512;
        let width = img.width;
        let height = img.height;

        if (width > height) {
          if (width > MAX_SIZE) {
            height *= MAX_SIZE / width;
            width = MAX_SIZE;
          }
        } else {
          if (height > MAX_SIZE) {
            width *= MAX_SIZE / height;
            height = MAX_SIZE;
          }
        }

        canvas.width = width;
        canvas.height = height;
        const ctx = canvas.getContext('2d');
        if (ctx) {
          ctx.drawImage(img, 0, 0, width, height);
          const dataUrl = canvas.toDataURL('image/png');
          setCustomIconUrl(dataUrl);
          setIconType('custom');
        }
      };
      img.src = event.target?.result as string;
    };
    reader.readAsDataURL(file);
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    const isFolder = bookmarkType === 'folder';
    const isNote = bookmarkType === 'note';
    if (title && (url || isFolder || isDashboardWidget || isNote)) {
      let formattedUrl = url;
      if (url && !/^https?:\/\//i.test(url)) {
        formattedUrl = 'https://' + url;
      }
      
      const iconProps = {
        iconType,
        lucideIcon: iconType === 'lucide' ? lucideIcon : undefined,
        iconColor: iconType === 'lucide' ? iconColor : undefined,
        customIconUrl: iconType === 'custom' ? customIconUrl : undefined,
        isDashboardWidget,
        useCoverIcon: isFolder ? useCoverIcon : undefined,
        isFullCover: isFolder ? isFullCover : undefined,
        type: bookmarkType,
        useCoverIcon: isFolder ? useCoverIcon : undefined,
        isFullCover: isFolder ? isFullCover : undefined,
        notes: isNote ? noteContent : (editData?.notes || ''),
        quickNote,
        useQuickNoteOnHover,
        pinToEnd
      };

      if (editData) {
        onEdit(editData.id, title, formattedUrl, iconProps);
      } else {
        onAdd(title, formattedUrl, iconProps);
      }
      
      onClose();
    }
  };

  return (
    <AnimatePresence>
      {isOpen && (
        <div className="modal-overlay" onClick={onClose} style={{ zIndex: 10000 }}>
          <motion.div
            initial={{ opacity: 0, scale: 0.9, y: 20 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.9, y: 20 }}
            className="glass modal-content"
            onClick={(e) => e.stopPropagation()}
            style={{ maxWidth: '500px', width: '90%', maxHeight: '90vh', overflowY: 'auto' }}
          >
            <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '24px' }}>
              <h2 style={{ fontSize: '20px', fontWeight: 600 }}>
                {editData 
                  ? (bookmarkType === 'folder' ? 'Edit Group' : (bookmarkType === 'note' ? 'Edit Note' : 'Edit Bookmark')) 
                  : (bookmarkType === 'folder' ? 'Add Group' : (bookmarkType === 'note' ? 'Add Note' : 'Add Bookmark'))}
              </h2>
              <button onClick={onClose} style={{ background: 'none', border: 'none', cursor: 'pointer' }}>
                <X size={20} color="rgba(255, 255, 255, 0.5)" />
              </button>
            </div>

            <form onSubmit={handleSubmit}>
              {!editData && (
                <div style={{ display: 'flex', gap: '8px', marginBottom: '24px', background: 'rgba(255,255,255,0.05)', padding: '4px', borderRadius: '12px' }}>
                  <button
                    type="button"
                    onClick={() => setBookmarkType('bookmark')}
                    style={{ flex: 1, padding: '8px', borderRadius: '8px', border: 'none', cursor: 'pointer', background: bookmarkType === 'bookmark' ? 'rgba(255,255,255,0.15)' : 'transparent', color: bookmarkType === 'bookmark' ? 'white' : 'rgba(255,255,255,0.5)', fontWeight: 500, transition: 'all 0.2s' }}
                  >
                    Bookmark
                  </button>
                  <button
                    type="button"
                    onClick={() => {
                      setBookmarkType('note');
                      setIconType('lucide');
                      setLucideIcon('StickyNote');
                      if (!title) setTitle('New Note');
                    }}
                    style={{ flex: 1, padding: '8px', borderRadius: '8px', border: 'none', cursor: 'pointer', background: bookmarkType === 'note' ? 'rgba(255,255,255,0.15)' : 'transparent', color: bookmarkType === 'note' ? 'white' : 'rgba(255,255,255,0.5)', fontWeight: 500, transition: 'all 0.2s' }}
                  >
                    Note
                  </button>
                  <button
                    type="button"
                    onClick={() => setBookmarkType('folder')}
                    style={{ flex: 1, padding: '8px', borderRadius: '8px', border: 'none', cursor: 'pointer', background: bookmarkType === 'folder' ? 'rgba(255,255,255,0.15)' : 'transparent', color: bookmarkType === 'folder' ? 'white' : 'rgba(255,255,255,0.5)', fontWeight: 500, transition: 'all 0.2s' }}
                  >
                    Group
                  </button>
                </div>
              )}

              <div style={{ display: 'flex', gap: '20px', marginBottom: '24px', alignItems: 'center' }}>
                <div style={{ flexShrink: 0 }}>
                  <BookmarkIcon
                    title={title || 'Preview'}
                    url={url}
                    iconType={iconType}
                    lucideIcon={lucideIcon}
                    iconColor={iconColor}
                    customIconUrl={customIconUrl}
                    size={64}
                  />
                </div>
                <div style={{ flexGrow: 1, display: 'flex', flexDirection: 'column', gap: '12px' }}>
                  <div className="form-group" style={{ marginBottom: 0, position: 'relative' }}>
                    <input
                      type="text"
                      className="form-input"
                      placeholder="Title"
                      value={title}
                      onChange={handleTitleChange}
                      required
                      autoFocus
                      style={{ paddingRight: isFetchingTitle ? '120px' : undefined }}
                    />
                    {isFetchingTitle && (
                      <span style={{
                        position: 'absolute',
                        right: '12px',
                        top: '50%',
                        transform: 'translateY(-50%)',
                        fontSize: '11px',
                        color: 'rgba(255,255,255,0.4)',
                        pointerEvents: 'none',
                        display: 'flex',
                        alignItems: 'center',
                        gap: '5px'
                      }}>
                        <span style={{ display: 'inline-block', width: '8px', height: '8px', borderRadius: '50%', border: '1.5px solid rgba(255,255,255,0.2)', borderTopColor: 'rgba(255,255,255,0.6)', animation: 'spin 0.7s linear infinite' }} />
                        Fetching title...
                      </span>
                    )}
                  </div>
                  {bookmarkType === 'note' && (
                    <div className="form-group" style={{ marginBottom: 0 }}>
                      <textarea
                        className="form-input"
                        placeholder="Write your note here..."
                        value={noteContent}
                        onChange={(e) => setNoteContent(e.target.value)}
                        style={{ minHeight: '100px', resize: 'vertical' }}
                      />
                    </div>
                  )}
                  {bookmarkType === 'bookmark' && !isDashboardWidget && (
                    <div className="form-group" style={{ marginBottom: 0 }}>
                      <input
                        type="text"
                        className="form-input"
                        placeholder="URL (e.g. google.com)"
                        value={url}
                        onChange={handleUrlChange}
                        required
                      />
                    </div>
                  )}
                  {bookmarkType !== 'folder' && (
                    <div 
                      className="form-group" 
                      style={{ 
                        marginBottom: 0, 
                        display: 'flex', 
                        alignItems: 'center', 
                      gap: '10px',
                      padding: '8px 12px',
                      background: 'rgba(255, 255, 255, 0.05)',
                      borderRadius: '12px',
                      cursor: 'pointer',
                      transition: 'background 0.2s'
                    }}
                    onClick={() => setIsDashboardWidget(!isDashboardWidget)}
                    onMouseEnter={(e) => e.currentTarget.style.background = 'rgba(255, 255, 255, 0.08)'}
                    onMouseLeave={(e) => e.currentTarget.style.background = 'rgba(255, 255, 255, 0.05)'}
                  >
                    <input
                      type="checkbox"
                      id="isDashboardWidget"
                      checked={isDashboardWidget}
                      onChange={(e) => {
                        e.stopPropagation();
                        setIsDashboardWidget(e.target.checked);
                      }}
                      style={{ 
                        width: '18px', 
                        height: '18px', 
                        cursor: 'pointer',
                        accentColor: 'var(--accent-color)'
                      }}
                    />
                    <label 
                      htmlFor="isDashboardWidget" 
                      style={{ 
                        fontSize: '14px', 
                        cursor: 'pointer', 
                        userSelect: 'none',
                        color: 'white',
                        fontWeight: 500,
                        flexGrow: 1
                      }}
                    >
                      Turn into Bookmark Dashboard
                    </label>
                  </div>
                )}
                  {(bookmarkType === 'bookmark' || bookmarkType === 'note') && (
                    <div style={{ display: 'flex', flexDirection: 'column', gap: '8px', marginTop: '4px' }}>
                      <div 
                        className="form-group" 
                        style={{ 
                          marginBottom: 0, 
                          display: 'flex', 
                          alignItems: 'center', 
                          gap: '10px',
                          padding: '8px 12px',
                          background: 'rgba(255, 255, 255, 0.05)',
                          borderRadius: '12px',
                          cursor: 'pointer',
                          transition: 'background 0.2s'
                        }}
                        onClick={() => setUseQuickNoteOnHover(!useQuickNoteOnHover)}
                      >
                        <input
                          type="checkbox"
                          checked={useQuickNoteOnHover}
                          onChange={(e) => {
                            e.stopPropagation();
                            setUseQuickNoteOnHover(e.target.checked);
                          }}
                          style={{ width: '18px', height: '18px', cursor: 'pointer' }}
                        />
                        <label style={{ fontSize: '14px', cursor: 'pointer', color: 'white', fontWeight: 500 }}>
                          Show Quick Note on Hover
                        </label>
                      </div>
                      
                      {useQuickNoteOnHover && (
                        <motion.div initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: 'auto' }}>
                          <textarea
                            className="form-input"
                            placeholder="Hover Note (Keep it short!)"
                            value={quickNote}
                            onChange={(e) => setQuickNote(e.target.value)}
                            style={{ minHeight: '60px', marginTop: '4px' }}
                          />
                        </motion.div>
                      )}

                    </div>
                  )}

                  <div 
                    className="form-group" 
                    style={{ 
                      marginBottom: 0, 
                      display: 'flex', 
                      alignItems: 'center', 
                      gap: '10px',
                      padding: '8px 12px',
                      background: 'rgba(255, 255, 255, 0.05)',
                      borderRadius: '12px',
                      cursor: 'pointer',
                      transition: 'background 0.2s',
                      marginTop: '8px'
                    }}
                    onClick={() => setPinToEnd(!pinToEnd)}
                  >
                    <input
                      type="checkbox"
                      checked={pinToEnd}
                      onChange={(e) => {
                        e.stopPropagation();
                        setPinToEnd(e.target.checked);
                      }}
                      style={{ width: '18px', height: '18px', cursor: 'pointer', accentColor: 'var(--accent-color)' }}
                    />
                    <label style={{ fontSize: '14px', cursor: 'pointer', color: 'white', fontWeight: 500 }}>
                      Always Stay at the End
                    </label>
                  </div>
                {bookmarkType === 'folder' && (
                    <div 
                      className="form-group" 
                      style={{ 
                        marginBottom: 0, 
                        display: 'flex', 
                        alignItems: 'center', 
                        gap: '10px',
                        padding: '8px 12px',
                        background: 'rgba(255, 255, 255, 0.05)',
                        borderRadius: '12px',
                        cursor: 'pointer',
                        transition: 'background 0.2s'
                      }}
                      onClick={() => setUseCoverIcon(!useCoverIcon)}
                      onMouseEnter={(e) => e.currentTarget.style.background = 'rgba(255, 255, 255, 0.08)'}
                      onMouseLeave={(e) => e.currentTarget.style.background = 'rgba(255, 255, 255, 0.05)'}
                    >
                      <input
                        type="checkbox"
                        id="useCoverIcon"
                        checked={useCoverIcon}
                        onChange={(e) => {
                          e.stopPropagation();
                          setUseCoverIcon(e.target.checked);
                        }}
                        style={{ 
                          width: '18px', 
                          height: '18px', 
                          cursor: 'pointer',
                          accentColor: 'var(--accent-color)'
                        }}
                      />
                      <label 
                        htmlFor="useCoverIcon" 
                        style={{ 
                          fontSize: '14px', 
                          cursor: 'pointer', 
                          userSelect: 'none',
                          color: 'white',
                          fontWeight: 500,
                          flexGrow: 1
                        }}
                      >
                        Use Cover Icon
                      </label>
                    </div>
                  )}
                  {bookmarkType === 'folder' && useCoverIcon && (
                    <div 
                      className="form-group" 
                      style={{ 
                        marginBottom: 0, 
                        display: 'flex', 
                        alignItems: 'center', 
                        gap: '10px',
                        padding: '8px 12px',
                        background: 'rgba(255, 255, 255, 0.05)',
                        borderRadius: '12px',
                        cursor: 'pointer',
                        transition: 'background 0.2s',
                        marginTop: '8px'
                      }}
                      onClick={() => setIsFullCover(!isFullCover)}
                      onMouseEnter={(e) => e.currentTarget.style.background = 'rgba(255, 255, 255, 0.08)'}
                      onMouseLeave={(e) => e.currentTarget.style.background = 'rgba(255, 255, 255, 0.05)'}
                    >
                      <input
                        type="checkbox"
                        id="isFullCover"
                        checked={isFullCover}
                        onChange={(e) => {
                          e.stopPropagation();
                          setIsFullCover(e.target.checked);
                        }}
                        style={{ 
                          width: '18px', 
                          height: '18px', 
                          cursor: 'pointer',
                          accentColor: 'var(--accent-color)'
                        }}
                      />
                      <label 
                        htmlFor="isFullCover" 
                        style={{ 
                          fontSize: '14px', 
                          cursor: 'pointer', 
                          userSelect: 'none',
                          color: 'white',
                          fontWeight: 500,
                          flexGrow: 1
                        }}
                      >
                        Full Cover Image (Hide Title)
                      </label>
                    </div>
                  )}
                </div>
              </div>

              <div className="form-group">
                <label>Icon Style</label>
                <div style={{ display: 'flex', gap: '10px', marginTop: '8px' }}>
                  <button 
                    type="button"
                    onClick={() => setIconType('favicon')}
                    style={{ 
                      flex: 1, padding: '10px', borderRadius: '8px', border: 'none', cursor: 'pointer',
                      background: iconType === 'favicon' ? 'rgba(255,255,255,0.2)' : 'rgba(255,255,255,0.05)',
                      color: 'white', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '6px'
                    }}
                  >
                    <Globe size={16} /> Favicon
                  </button>
                  <button 
                    type="button"
                    onClick={() => setIconType('lucide')}
                    style={{ 
                      flex: 1, padding: '10px', borderRadius: '8px', border: 'none', cursor: 'pointer',
                      background: iconType === 'lucide' ? 'rgba(255,255,255,0.2)' : 'rgba(255,255,255,0.05)',
                      color: 'white', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '6px'
                    }}
                  >
                    <Star size={16} /> Icon Pack
                  </button>
                  <button 
                    type="button"
                    onClick={() => fileInputRef.current?.click()}
                    style={{ 
                      flex: 1, padding: '10px', borderRadius: '8px', border: 'none', cursor: 'pointer',
                      background: iconType === 'custom' ? 'rgba(255,255,255,0.2)' : 'rgba(255,255,255,0.05)',
                      color: 'white', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '6px'
                    }}
                  >
                    <Upload size={16} /> Upload
                  </button>
                  <input 
                    type="file" 
                    accept="image/*" 
                    ref={fileInputRef} 
                    style={{ display: 'none' }} 
                    onChange={handleImageUpload}
                  />
                </div>
              </div>

              {iconType === 'lucide' && (
                <motion.div initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: 'auto' }}>
                  <div className="form-group" style={{ marginTop: '16px' }}>
                    <label>Choose Color</label>
                    <div style={{ display: 'flex', gap: '8px', marginTop: '8px', flexWrap: 'wrap' }}>
                      {PRESET_COLORS.map(c => (
                        <div 
                          key={c}
                          onClick={() => setIconColor(c)}
                          style={{
                            width: '24px', height: '24px', borderRadius: '50%', backgroundColor: c, cursor: 'pointer',
                            border: iconColor === c ? '2px solid white' : '2px solid transparent',
                            boxShadow: iconColor === c ? '0 0 10px rgba(255,255,255,0.5)' : 'none'
                          }}
                        />
                      ))}
                      <input 
                        type="color" 
                        value={iconColor} 
                        onChange={(e) => setIconColor(e.target.value)}
                        style={{ width: '24px', height: '24px', padding: 0, border: 'none', borderRadius: '4px', cursor: 'pointer', background: 'transparent' }}
                      />
                    </div>
                  </div>
                  
                  <div className="form-group" style={{ marginTop: '16px' }}>
                    <label>Choose Icon</label>
                    <div style={{ 
                      display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(40px, 1fr))', 
                      gap: '8px', marginTop: '8px', maxHeight: '150px', overflowY: 'auto', padding: '4px' 
                    }}>
                      {COMMON_ICONS.map(iconName => {
                        // Dynamically require is hard in Vite, but we imported them. We can just use the name if we imported it?
                        // Wait, we need to map names to actual imported components.
                        return (
                          <div 
                            key={iconName}
                            onClick={() => setLucideIcon(iconName)}
                            style={{
                              display: 'flex', alignItems: 'center', justifyContent: 'center',
                              padding: '8px', borderRadius: '8px', cursor: 'pointer',
                              background: lucideIcon === iconName ? 'rgba(255,255,255,0.2)' : 'rgba(255,255,255,0.05)',
                              border: lucideIcon === iconName ? '1px solid rgba(255,255,255,0.5)' : '1px solid transparent'
                            }}
                          >
                            <BookmarkIcon 
                              title="" url="" iconType="lucide" lucideIcon={iconName} iconColor={lucideIcon === iconName ? iconColor : '#ffffff'} size={24} noBackground 
                            />
                          </div>
                        )
                      })}
                    </div>
                  </div>
                </motion.div>
              )}

              <button type="submit" className="primary-button" style={{ marginTop: '24px' }}>
                {editData 
                  ? (editData.type === 'folder' ? 'Save Group' : 'Save Changes') 
                  : (bookmarkType === 'folder' ? 'Create Group' : 'Add Bookmark')}
              </button>
            </form>
          </motion.div>
        </div>
      )}
    </AnimatePresence>
  );
};

export default AddBookmarkModal;
